#
# Module manifest for module 'PowerNetbox'
#
# Generated by: Ben Claussen, ctrl-alt-automate
#
# Generated on: 4/17/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PowerNetbox.psm1'

# Version number of this module.
ModuleVersion = '4.6.0.2'

# Supported PSEditions
CompatiblePSEditions = 'Desktop', 'Core'

# ID used to uniquely identify this module
GUID = 'de71bbf6-b290-44a5-9c3a-f5c28c3bb79f'

# Author of this module
Author = 'Ben Claussen, ctrl-alt-automate'

# Company or vendor of this module
CompanyName = 'ctrl-alt-automate'

# Copyright statement for this module
Copyright = '(c) 2018-2026 Ben Claussen and contributors. Fork maintained by ctrl-alt-automate.'

# Description of the functionality provided by this module
Description = 'PowerNetbox - The comprehensive PowerShell module for Netbox REST API with 100% coverage. Fork of NetboxPS (Ben Claussen) with full Netbox 4.x compatibility. 488+ functions for DCIM, IPAM, Virtualization, Circuits, Tenancy, VPN, Wireless, Extras, Core, Users. Cross-platform (Windows, Linux, macOS).'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '2.0'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
ClrVersion = '2.0.50727'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'AssertNBMutualExclusiveParam', 'BuildNewURI', 'BuildURIComponents',
               'CheckNetboxIsConnected', 'Clear-NBCredential', 'Connect-NBAPI',
               'ConvertTo-NBRackConsole', 'ConvertTo-NBRackHTML',
               'ConvertTo-NBRackMarkdown', 'ConvertTo-NetboxVersion',
               'Enter-NBBranch', 'Exit-NBBranch', 'Export-NBRackElevation',
               'Get-NBAPIDefinition', 'Get-NBBookmark', 'Get-NBBranch',
               'Get-NBBranchContext', 'Get-NBBranchEvent', 'Get-NBChangeDiff',
               'Get-NBCircuit', 'Get-NBCircuitGroup', 'Get-NBCircuitGroupAssignment',
               'Get-NBCircuitProvider', 'Get-NBCircuitProviderAccount',
               'Get-NBCircuitProviderNetwork', 'Get-NBCircuitTermination',
               'Get-NBCircuitType', 'Get-NBConfigContext', 'Get-NBContact',
               'Get-NBContactAssignment', 'Get-NBContactRole', 'Get-NBContentType',
               'Get-NBCredential', 'Get-NBCustomField', 'Get-NBCustomFieldChoiceSet',
               'Get-NBCustomLink', 'Get-NBDataFile', 'Get-NBDataSource',
               'Get-NBDCIMCable', 'Get-NBDCIMCableTermination',
               'Get-NBDCIMConnectedDevice', 'Get-NBDCIMConsolePort',
               'Get-NBDCIMConsolePortTemplate', 'Get-NBDCIMConsoleServerPort',
               'Get-NBDCIMConsoleServerPortTemplate', 'Get-NBDCIMDevice',
               'Get-NBDCIMDeviceBay', 'Get-NBDCIMDeviceBayTemplate',
               'Get-NBDCIMDeviceRole', 'Get-NBDCIMDeviceType', 'Get-NBDCIMFrontPort',
               'Get-NBDCIMFrontPortTemplate', 'Get-NBDCIMInterface',
               'Get-NBDCIMInterfaceTemplate', 'Get-NBDCIMInventoryItem',
               'Get-NBDCIMInventoryItemRole', 'Get-NBDCIMInventoryItemTemplate',
               'Get-NBDCIMLocation', 'Get-NBDCIMMACAddress',
               'Get-NBDCIMManufacturer', 'Get-NBDCIMModule', 'Get-NBDCIMModuleBay',
               'Get-NBDCIMModuleBayTemplate', 'Get-NBDCIMModuleType',
               'Get-NBDCIMModuleTypeProfile', 'Get-NBDCIMPlatform',
               'Get-NBDCIMPowerFeed', 'Get-NBDCIMPowerOutlet',
               'Get-NBDCIMPowerOutletTemplate', 'Get-NBDCIMPowerPanel',
               'Get-NBDCIMPowerPort', 'Get-NBDCIMPowerPortTemplate',
               'Get-NBDCIMRack', 'Get-NBDCIMRackElevation',
               'Get-NBDCIMRackReservation', 'Get-NBDCIMRackRole',
               'Get-NBDCIMRackType', 'Get-NBDCIMRearPort',
               'Get-NBDCIMRearPortTemplate', 'Get-NBDCIMRegion', 'Get-NBDCIMSite',
               'Get-NBDCIMSiteGroup', 'Get-NBDCIMVirtualChassis',
               'Get-NBDCIMVirtualDeviceContext', 'Get-NBEventRule',
               'Get-NBExportTemplate', 'Get-NBGroup', 'Get-NBHostname',
               'Get-NBHostPort', 'Get-NBHostScheme', 'Get-NBImageAttachment',
               'Get-NBInvokeParams', 'Get-NBIPAMAddress', 'Get-NBIPAMAddressRange',
               'Get-NBIPAMAggregate', 'Get-NBIPAMASN', 'Get-NBIPAMASNRange',
               'Get-NBIPAMAvailableIP', 'Get-NBIPAMFHRPGroup',
               'Get-NBIPAMFHRPGroupAssignment', 'Get-NBIPAMPrefix', 'Get-NBIPAMRIR',
               'Get-NBIPAMRole', 'Get-NBIPAMRouteTarget', 'Get-NBIPAMService',
               'Get-NBIPAMServiceTemplate', 'Get-NBIPAMVLAN', 'Get-NBIPAMVLANGroup',
               'Get-NBIPAMVLANTranslationPolicy', 'Get-NBIPAMVLANTranslationRule',
               'Get-NBIPAMVRF', 'Get-NBJob', 'Get-NBJournalEntry',
               'Get-NBObjectChange', 'Get-NBObjectType', 'Get-NBOwner',
               'Get-NBOwnerGroup', 'Get-NBPermission', 'Get-NBRequestHeaders',
               'Get-NBSavedFilter', 'Get-NBTag', 'Get-NBTenant', 'Get-NBTenantGroup',
               'Get-NBTimeout', 'Get-NBToken', 'Get-NBUser', 'Get-NBVersion',
               'Get-NBVirtualCircuit', 'Get-NBVirtualCircuitTermination',
               'Get-NBVirtualCircuitType', 'Get-NBVirtualizationCluster',
               'Get-NBVirtualizationClusterGroup',
               'Get-NBVirtualizationClusterType', 'Get-NBVirtualMachine',
               'Get-NBVirtualMachineInterface', 'Get-NBVPNIKEPolicy',
               'Get-NBVPNIKEProposal', 'Get-NBVPNIPSecPolicy',
               'Get-NBVPNIPSecProfile', 'Get-NBVPNIPSecProposal', 'Get-NBVPNL2VPN',
               'Get-NBVPNL2VPNTermination', 'Get-NBVPNTunnel',
               'Get-NBVPNTunnelGroup', 'Get-NBVPNTunnelTermination', 'Get-NBWebhook',
               'Get-NBWirelessLAN', 'Get-NBWirelessLANGroup', 'Get-NBWirelessLink',
               'GetNetboxAPIErrorBody', 'GetNetboxConfigVariable',
               'Invoke-NBGraphQL', 'Invoke-NBInBranch', 'InvokeNetboxRequest',
               'Merge-NBBranch', 'New-NBBookmark', 'New-NBBranch', 'New-NBCircuit',
               'New-NBCircuitGroup', 'New-NBCircuitGroupAssignment',
               'New-NBCircuitProvider', 'New-NBCircuitProviderAccount',
               'New-NBCircuitProviderNetwork', 'New-NBCircuitTermination',
               'New-NBCircuitType', 'New-NBConfigContext', 'New-NBContact',
               'New-NBContactAssignment', 'New-NBContactRole', 'New-NBCustomField',
               'New-NBCustomFieldChoiceSet', 'New-NBCustomLink', 'New-NBDataSource',
               'New-NBDCIMCable', 'New-NBDCIMConsolePort',
               'New-NBDCIMConsolePortTemplate', 'New-NBDCIMConsoleServerPort',
               'New-NBDCIMConsoleServerPortTemplate', 'New-NBDCIMDevice',
               'New-NBDCIMDeviceBay', 'New-NBDCIMDeviceBayTemplate',
               'New-NBDCIMDeviceRole', 'New-NBDCIMDeviceType', 'New-NBDCIMFrontPort',
               'New-NBDCIMFrontPortTemplate', 'New-NBDCIMInterface',
               'New-NBDCIMInterfaceTemplate', 'New-NBDCIMInventoryItem',
               'New-NBDCIMInventoryItemRole', 'New-NBDCIMInventoryItemTemplate',
               'New-NBDCIMLocation', 'New-NBDCIMMACAddress',
               'New-NBDCIMManufacturer', 'New-NBDCIMModule', 'New-NBDCIMModuleBay',
               'New-NBDCIMModuleBayTemplate', 'New-NBDCIMModuleType',
               'New-NBDCIMModuleTypeProfile', 'New-NBDCIMPlatform',
               'New-NBDCIMPowerFeed', 'New-NBDCIMPowerOutlet',
               'New-NBDCIMPowerOutletTemplate', 'New-NBDCIMPowerPanel',
               'New-NBDCIMPowerPort', 'New-NBDCIMPowerPortTemplate',
               'New-NBDCIMRack', 'New-NBDCIMRackReservation', 'New-NBDCIMRackRole',
               'New-NBDCIMRackType', 'New-NBDCIMRearPort',
               'New-NBDCIMRearPortTemplate', 'New-NBDCIMRegion', 'New-NBDCIMSite',
               'New-NBDCIMSiteGroup', 'New-NBDCIMVirtualChassis',
               'New-NBDCIMVirtualDeviceContext', 'New-NBEventRule',
               'New-NBExportTemplate', 'New-NBGroup', 'New-NBImageAttachment',
               'New-NBIPAMAddress', 'New-NBIPAMAddressRange', 'New-NBIPAMAggregate',
               'New-NBIPAMASN', 'New-NBIPAMASNRange', 'New-NBIPAMFHRPGroup',
               'New-NBIPAMFHRPGroupAssignment', 'New-NBIPAMPrefix', 'New-NBIPAMRIR',
               'New-NBIPAMRole', 'New-NBIPAMRouteTarget', 'New-NBIPAMService',
               'New-NBIPAMServiceTemplate', 'New-NBIPAMVLAN', 'New-NBIPAMVLANGroup',
               'New-NBIPAMVLANTranslationPolicy', 'New-NBIPAMVLANTranslationRule',
               'New-NBIPAMVRF', 'New-NBJournalEntry', 'New-NBOwner',
               'New-NBOwnerGroup', 'New-NBPermission', 'New-NBSavedFilter',
               'New-NBTag', 'New-NBTenant', 'New-NBTenantGroup', 'New-NBToken',
               'New-NBUser', 'New-NBVirtualCircuit',
               'New-NBVirtualCircuitTermination', 'New-NBVirtualCircuitType',
               'New-NBVirtualizationCluster', 'New-NBVirtualizationClusterGroup',
               'New-NBVirtualizationClusterType', 'New-NBVirtualMachine',
               'New-NBVirtualMachineInterface', 'New-NBVPNIKEPolicy',
               'New-NBVPNIKEProposal', 'New-NBVPNIPSecPolicy',
               'New-NBVPNIPSecProfile', 'New-NBVPNIPSecProposal', 'New-NBVPNL2VPN',
               'New-NBVPNL2VPNTermination', 'New-NBVPNTunnel',
               'New-NBVPNTunnelGroup', 'New-NBVPNTunnelTermination', 'New-NBWebhook',
               'New-NBWirelessLAN', 'New-NBWirelessLANGroup', 'New-NBWirelessLink',
               'Remove-NBBookmark', 'Remove-NBBranch', 'Remove-NBCircuit',
               'Remove-NBCircuitGroup', 'Remove-NBCircuitGroupAssignment',
               'Remove-NBCircuitProvider', 'Remove-NBCircuitProviderAccount',
               'Remove-NBCircuitProviderNetwork', 'Remove-NBCircuitTermination',
               'Remove-NBCircuitType', 'Remove-NBConfigContext', 'Remove-NBContact',
               'Remove-NBContactAssignment', 'Remove-NBContactRole',
               'Remove-NBCustomField', 'Remove-NBCustomFieldChoiceSet',
               'Remove-NBCustomLink', 'Remove-NBDataSource', 'Remove-NBDCIMCable',
               'Remove-NBDCIMConsolePort', 'Remove-NBDCIMConsolePortTemplate',
               'Remove-NBDCIMConsoleServerPort',
               'Remove-NBDCIMConsoleServerPortTemplate', 'Remove-NBDCIMDevice',
               'Remove-NBDCIMDeviceBay', 'Remove-NBDCIMDeviceBayTemplate',
               'Remove-NBDCIMDeviceRole', 'Remove-NBDCIMDeviceType',
               'Remove-NBDCIMFrontPort', 'Remove-NBDCIMFrontPortTemplate',
               'Remove-NBDCIMInterface', 'Remove-NBDCIMInterfaceTemplate',
               'Remove-NBDCIMInventoryItem', 'Remove-NBDCIMInventoryItemRole',
               'Remove-NBDCIMInventoryItemTemplate', 'Remove-NBDCIMLocation',
               'Remove-NBDCIMMACAddress', 'Remove-NBDCIMManufacturer',
               'Remove-NBDCIMModule', 'Remove-NBDCIMModuleBay',
               'Remove-NBDCIMModuleBayTemplate', 'Remove-NBDCIMModuleType',
               'Remove-NBDCIMModuleTypeProfile', 'Remove-NBDCIMPlatform',
               'Remove-NBDCIMPowerFeed', 'Remove-NBDCIMPowerOutlet',
               'Remove-NBDCIMPowerOutletTemplate', 'Remove-NBDCIMPowerPanel',
               'Remove-NBDCIMPowerPort', 'Remove-NBDCIMPowerPortTemplate',
               'Remove-NBDCIMRack', 'Remove-NBDCIMRackReservation',
               'Remove-NBDCIMRackRole', 'Remove-NBDCIMRackType',
               'Remove-NBDCIMRearPort', 'Remove-NBDCIMRearPortTemplate',
               'Remove-NBDCIMRegion', 'Remove-NBDCIMSite', 'Remove-NBDCIMSiteGroup',
               'Remove-NBDCIMVirtualChassis', 'Remove-NBDCIMVirtualDeviceContext',
               'Remove-NBEventRule', 'Remove-NBExportTemplate', 'Remove-NBGroup',
               'Remove-NBImageAttachment', 'Remove-NBIPAMAddress',
               'Remove-NBIPAMAddressRange', 'Remove-NBIPAMAggregate',
               'Remove-NBIPAMASN', 'Remove-NBIPAMASNRange', 'Remove-NBIPAMFHRPGroup',
               'Remove-NBIPAMFHRPGroupAssignment', 'Remove-NBIPAMPrefix',
               'Remove-NBIPAMRIR', 'Remove-NBIPAMRole', 'Remove-NBIPAMRouteTarget',
               'Remove-NBIPAMService', 'Remove-NBIPAMServiceTemplate',
               'Remove-NBIPAMVLAN', 'Remove-NBIPAMVLANGroup',
               'Remove-NBIPAMVLANTranslationPolicy',
               'Remove-NBIPAMVLANTranslationRule', 'Remove-NBIPAMVRF',
               'Remove-NBJournalEntry', 'Remove-NBOwner', 'Remove-NBOwnerGroup',
               'Remove-NBPermission', 'Remove-NBSavedFilter', 'Remove-NBTag',
               'Remove-NBTenant', 'Remove-NBTenantGroup', 'Remove-NBToken',
               'Remove-NBUser', 'Remove-NBVirtualCircuit',
               'Remove-NBVirtualCircuitTermination', 'Remove-NBVirtualCircuitType',
               'Remove-NBVirtualizationCluster',
               'Remove-NBVirtualizationClusterGroup',
               'Remove-NBVirtualizationClusterType', 'Remove-NBVirtualMachine',
               'Remove-NBVirtualMachineInterface', 'Remove-NBVPNIKEPolicy',
               'Remove-NBVPNIKEProposal', 'Remove-NBVPNIPSecPolicy',
               'Remove-NBVPNIPSecProfile', 'Remove-NBVPNIPSecProposal',
               'Remove-NBVPNL2VPN', 'Remove-NBVPNL2VPNTermination',
               'Remove-NBVPNTunnel', 'Remove-NBVPNTunnelGroup',
               'Remove-NBVPNTunnelTermination', 'Remove-NBWebhook',
               'Remove-NBWirelessLAN', 'Remove-NBWirelessLANGroup',
               'Remove-NBWirelessLink', 'Send-NBBulkRequest', 'Set-NBBranch',
               'Set-NBCipherSSL', 'Set-NBCircuit', 'Set-NBCircuitGroup',
               'Set-NBCircuitGroupAssignment', 'Set-NBCircuitProvider',
               'Set-NBCircuitProviderAccount', 'Set-NBCircuitProviderNetwork',
               'Set-NBCircuitTermination', 'Set-NBCircuitType',
               'Set-NBConfigContext', 'Set-NBContact', 'Set-NBContactAssignment',
               'Set-NBContactRole', 'Set-NBCredential', 'Set-NBCustomField',
               'Set-NBCustomFieldChoiceSet', 'Set-NBCustomLink', 'Set-NBDataSource',
               'Set-NBDCIMCable', 'Set-NBDCIMConsolePort',
               'Set-NBDCIMConsolePortTemplate', 'Set-NBDCIMConsoleServerPort',
               'Set-NBDCIMConsoleServerPortTemplate', 'Set-NBDCIMDevice',
               'Set-NBDCIMDeviceBay', 'Set-NBDCIMDeviceBayTemplate',
               'Set-NBDCIMDeviceRole', 'Set-NBDCIMDeviceType', 'Set-NBDCIMFrontPort',
               'Set-NBDCIMFrontPortTemplate', 'Set-NBDCIMInterface',
               'Set-NBDCIMInterfaceTemplate', 'Set-NBDCIMInventoryItem',
               'Set-NBDCIMInventoryItemRole', 'Set-NBDCIMInventoryItemTemplate',
               'Set-NBDCIMLocation', 'Set-NBDCIMMACAddress',
               'Set-NBDCIMManufacturer', 'Set-NBDCIMModule', 'Set-NBDCIMModuleBay',
               'Set-NBDCIMModuleBayTemplate', 'Set-NBDCIMModuleType',
               'Set-NBDCIMModuleTypeProfile', 'Set-NBDCIMPlatform',
               'Set-NBDCIMPowerFeed', 'Set-NBDCIMPowerOutlet',
               'Set-NBDCIMPowerOutletTemplate', 'Set-NBDCIMPowerPanel',
               'Set-NBDCIMPowerPort', 'Set-NBDCIMPowerPortTemplate',
               'Set-NBDCIMRack', 'Set-NBDCIMRackReservation', 'Set-NBDCIMRackRole',
               'Set-NBDCIMRackType', 'Set-NBDCIMRearPort',
               'Set-NBDCIMRearPortTemplate', 'Set-NBDCIMRegion', 'Set-NBDCIMSite',
               'Set-NBDCIMSiteGroup', 'Set-NBDCIMVirtualChassis',
               'Set-NBDCIMVirtualDeviceContext', 'Set-NBEventRule',
               'Set-NBExportTemplate', 'Set-NBGroup', 'Set-NBHostName',
               'Set-NBHostPort', 'Set-NBHostScheme', 'Set-NBInvokeParams',
               'Set-NBIPAMAddress', 'Set-NBIPAMAddressRange', 'Set-NBIPAMAggregate',
               'Set-NBIPAMASN', 'Set-NBIPAMASNRange', 'Set-NBIPAMFHRPGroup',
               'Set-NBIPAMFHRPGroupAssignment', 'Set-NBIPAMPrefix', 'Set-NBIPAMRIR',
               'Set-NBIPAMRole', 'Set-NBIPAMRouteTarget', 'Set-NBIPAMService',
               'Set-NBIPAMServiceTemplate', 'Set-NBIPAMVLAN', 'Set-NBIPAMVLANGroup',
               'Set-NBIPAMVLANTranslationPolicy', 'Set-NBIPAMVLANTranslationRule',
               'Set-NBIPAMVRF', 'Set-NBJournalEntry', 'Set-NBOwner',
               'Set-NBOwnerGroup', 'Set-NBPermission', 'Set-NBSavedFilter',
               'Set-NBTag', 'Set-NBTenant', 'Set-NBTenantGroup', 'Set-NBTimeout',
               'Set-NBToken', 'Set-NBuntrustedSSL', 'Set-NBUser',
               'Set-NBVirtualCircuit', 'Set-NBVirtualCircuitTermination',
               'Set-NBVirtualCircuitType', 'Set-NBVirtualizationCluster',
               'Set-NBVirtualizationClusterGroup',
               'Set-NBVirtualizationClusterType', 'Set-NBVirtualMachine',
               'Set-NBVirtualMachineInterface', 'Set-NBVPNIKEPolicy',
               'Set-NBVPNIKEProposal', 'Set-NBVPNIPSecPolicy',
               'Set-NBVPNIPSecProfile', 'Set-NBVPNIPSecProposal', 'Set-NBVPNL2VPN',
               'Set-NBVPNL2VPNTermination', 'Set-NBVPNTunnel',
               'Set-NBVPNTunnelGroup', 'Set-NBVPNTunnelTermination', 'Set-NBWebhook',
               'Set-NBWirelessLAN', 'Set-NBWirelessLANGroup', 'Set-NBWirelessLink',
               'SetupNetboxConfigVariable', 'Sync-NBBranch', 'Test-NBAPIConnected',
               'Test-NBAuthentication', 'Test-NBBranchingAvailable',
               'Test-NBDeprecatedParameter', 'Test-NBMinimumVersion',
               'Undo-NBBranchMerge', 'VerifyAPIConnectivity', 'Wait-NBBranch'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Add-NBDCIMInterface', 'Add-NBDCIMFrontPort', 'Add-NBDCIMRearPort',
               'Add-NBVirtualMachineInterface'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Netbox','PowerNetbox','NetboxAPI','API','REST','DCIM','IPAM','Infrastructure','Automation','NetworkAutomation','DataCenter','Virtualization','VPN','Wireless','AssetManagement','CrossPlatform','Linux','MacOS','Windows','PowerShell'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/ctrl-alt-automate/PowerNetbox/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/ctrl-alt-automate/PowerNetbox'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'v4.5.2.0 - PowerNetbox Release (matches Netbox 4.5.2)
- Full Netbox 4.5.2 compatibility with netbox-docker 4.0.0
- CI migrated to netbox-docker 4.0.0 (Granian, PostgreSQL 18, Valkey 9)
- Security: Verbose logging redacts sensitive fields (#228)
- Security: Webhook Secret uses SecureString (#230)
- Security: AllowInsecureRedirect only with SkipCertificateCheck (#231)
- 524 public functions with 100% API coverage
- 1436 unit tests, 98 integration tests
- Cross-platform support (Windows, Linux, macOS)
- See https://github.com/ctrl-alt-automate/PowerNetbox/releases for full changelog'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

