function ConvertTo-NBRackMarkdown {
<#
    .SYNOPSIS
        Convert rack elevation data to Markdown format

    .DESCRIPTION
        Internal helper function that generates a GitHub-flavored markdown
        table representing a rack elevation diagram.

    .PARAMETER RackName
        Display name of the rack

    .PARAMETER SiteName
        Display name of the site

    .PARAMETER UHeight
        Total height of the rack in U

    .PARAMETER Face
        Face being displayed (Front or Rear)

    .PARAMETER ElevationData
        Array of elevation unit objects from Get-NBDCIMRackElevation

    .EXAMPLE
        $elevation = Get-NBDCIMRackElevation -Id 24
        ConvertTo-NBRackMarkdown -RackName "DC1-R01" -SiteName "Amsterdam" -UHeight 42 -Face Front -ElevationData $elevation

        Generates a GitHub-flavored markdown table showing rack elevation.

    .EXAMPLE
        $elevation = Get-NBDCIMRackElevation -Id 24 | Where-Object { $_.device }
        ConvertTo-NBRackMarkdown -RackName "DC1-R01" -SiteName "Amsterdam" -UHeight 42 -Face Front -ElevationData $elevation | Out-File rack.md -Encoding utf8

        Generates markdown for only occupied rack units and saves to file.

    .NOTES
    AddedInVersion: v4.4.10.0
        This is an internal helper function. Use Export-NBRackElevation -Format Markdown for the public interface.
#>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [string]$RackName,

        [string]$SiteName = '',

        [int]$UHeight = 42,

        [string]$Face = 'Front',

        [PSCustomObject[]]$ElevationData
    )

    $sb = [System.Text.StringBuilder]::new()

    # Header
    [void]$sb.AppendLine("## $RackName - $Face Face")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("**Site:** $SiteName | **Height:** ${UHeight}U")
    [void]$sb.AppendLine()

    # Table header
    [void]$sb.AppendLine("| U# | Device | Description |")
    [void]$sb.AppendLine("|---:|--------|-------------|")

    # Create a lookup of devices by position
    $deviceLookup = @{}
    foreach ($unit in $ElevationData) {
        if ($unit.device) {
            $deviceLookup[[int]$unit.id] = $unit
        }
    }

    # Generate rows from top to bottom
    for ($u = $UHeight; $u -ge 1; $u--) {
        $unit = $deviceLookup[$u]

        if ($unit -and $unit.device) {
            $deviceName = $unit.device.display -replace '\|', '\|'
            $deviceDesc = if ($unit.device.description) {
                $unit.device.description -replace '\|', '\|'
            } else {
                '-'
            }

            [void]$sb.AppendLine("| $u | **$deviceName** | $deviceDesc |")
        }
        else {
            [void]$sb.AppendLine("| $u | - | - |")
        }
    }

    [void]$sb.AppendLine()
    [void]$sb.AppendLine("---")
    [void]$sb.AppendLine("*Generated by PowerNetbox | $(Get-Date -Format 'yyyy-MM-dd HH:mm')*")

    return $sb.ToString()
}
